### ISSUE TITLE
Hypatia needs an icon

### ISSUE THREAD

**Issue by nathandyer** [HypatiaProject/hypatia#1]
Hypatia is nearing its first release, but does not yet have an icon, and my icon making skills are essentially non-existent.

If anyone would like to contribute to the project by making an icon, it would be greatly appreciated! 

Generally speaking, I'd like for it to have a GNOME-style icon (so it fits in well with other GNOME apps, and looks nice in Flathub/GNOME Software).

In terms of a metaphor, I'm not especially picky. I don't want it to be a "magnifying glass" icon, because that metaphor for searching is a bit tired (I don't think I've ever used a magnifying glass when searching for something in real life). While brainstorming, I found this image of a library card catalog, which I think might be a good metaphor:

![](https://www.signals.com/graphics/products/zoom/HA2022PO.jpg)

But I leave the creative decisions up to whomever is able to make the icon.

If you'd like to contribute, please feel free to make a pull request. If you have questions or want feedback, please leave a comment here. And of course, thank you so much to anyone who contributes!

**Comment by Suzie97** [comment]
@nathandyer As per my understanding, the app shows information on specific selected words. Like Lookup on apple devices. So I thought it would make sense to do a blueprint of an information icon. Let me know what you think about this.

![Hypatia Blueprint Icon 128](https://user-images.githubusercontent.com/68198116/159085191-4a8bd5a3-4ce9-48b6-8ec8-f9569b7aae11.svg)

**Comment by nathandyer** [comment]
@Suzie97 Excellent work! Your understanding is correct, and I like where it's heading. There are a couple of minor things that I want to be careful of here:

* The blueprint concept usually indicates either that something is meant for software development, or is in a non-stable (in development) state, so I think it's best to try and avoid anything with blueprints.
* I'm concerned that the exclamation point might indicate that something is an error (it's used in places like Gtk.Diaglogs as an icon when there's an error or something is wrong). I'm a bit concerned that people might see that and think they are seeing an alert.

That said, stylistically, I like it! If you have a moment to try another revision without those items I mentioned above, I'd be really curious to see it! Great work so far! Thanks!

**Comment by bertob** [comment]
Quick experiment trying the drawer thing:

![image](https://user-images.githubusercontent.com/1908896/159728298-e2de38b2-c49e-4ed4-866b-dc4cd224a528.png)

**Comment by nathandyer** [comment]
@bertob Thank you so much! I absolutely love that! If you want to file a PR, I'm happy and ready to merge!

**Comment by Suzie97** [comment]
> Quick experiment trying the drawer thing:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1908896/159728298-e2de38b2-c49e-4ed4-866b-dc4cd224a528.png)
> 
> 

Maybe we could try a different angle showing some of the documents (paper) inside the drawers. Just showing drawers kind of feels abstract. Anything could be inside those drawers

**Comment by nathandyer** [comment]
@Suzie97 That's a good point, although in a way I kind of like the ambiguity. It gives a sense that you don't know what you will find inside, which is useful for a tool where you can look up anything.

**Comment by Suzie97** [comment]
> @Suzie97 That's a good point, although in a way I kind of like the ambiguity. It gives a sense that you don't know what you will find inside, which is useful for a tool where you can look up anything.

Oh I didn't know that. I thought it was just for text
